// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX58f9oNLNvaych27NCOM3_Eqr89GAIhk',
    appId: '1:960075612405:web:61fe8fde3d9de526a305bc',
    messagingSenderId: '960075612405',
    projectId: 'flutter-expense-tracker-d1dc9',
    authDomain: 'flutter-expense-tracker-d1dc9.firebaseapp.com',
    storageBucket: 'flutter-expense-tracker-d1dc9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyqE-NdzAdV4eq1BPZAW2vF0loNAr6VeM',
    appId: '1:960075612405:android:0d6fa7c587be13e8a305bc',
    messagingSenderId: '960075612405',
    projectId: 'flutter-expense-tracker-d1dc9',
    storageBucket: 'flutter-expense-tracker-d1dc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf8Q8EKy1YWaqLJSpTMlFnBpClaoojVCM',
    appId: '1:960075612405:ios:27d5dd127b7977f5a305bc',
    messagingSenderId: '960075612405',
    projectId: 'flutter-expense-tracker-d1dc9',
    storageBucket: 'flutter-expense-tracker-d1dc9.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf8Q8EKy1YWaqLJSpTMlFnBpClaoojVCM',
    appId: '1:960075612405:ios:27d5dd127b7977f5a305bc',
    messagingSenderId: '960075612405',
    projectId: 'flutter-expense-tracker-d1dc9',
    storageBucket: 'flutter-expense-tracker-d1dc9.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX58f9oNLNvaych27NCOM3_Eqr89GAIhk',
    appId: '1:960075612405:web:5b5c4560b690bbdea305bc',
    messagingSenderId: '960075612405',
    projectId: 'flutter-expense-tracker-d1dc9',
    authDomain: 'flutter-expense-tracker-d1dc9.firebaseapp.com',
    storageBucket: 'flutter-expense-tracker-d1dc9.firebasestorage.app',
  );

}